"""Integration tests for owner claim preservation across token refresh.

Proves that:
1. An initial AKM token includes the owner claim.
2. A refreshed AKM token also includes the owner claim.
3. Agent shared retrieval still works after token refresh.
"""

import hashlib
import time
import uuid

import jwt
import pytest

pytestmark = pytest.mark.integration


class TestRefreshOwnerClaim:
    async def test_initial_token_includes_owner(self, ed25519_keypair):
        """Initial AKM token (as generated by API service) includes owner claim."""
        private_pem, public_pem = ed25519_keypair
        now = int(time.time())
        owner_sub = "user-abc-123"

        token = jwt.encode(
            {
                "sub": "agent-1",
                "iss": "hill90-api",
                "aud": "hill90-akm",
                "exp": now + 3600,
                "iat": now,
                "jti": str(uuid.uuid4()),
                "scopes": ["akm:read", "akm:write"],
                "owner": owner_sub,
            },
            private_pem,
            algorithm="EdDSA",
        )

        # Decode and verify owner is present
        decoded = jwt.decode(
            token,
            public_pem,
            algorithms=["EdDSA"],
            issuer="hill90-api",
            audience="hill90-akm",
        )
        assert decoded["owner"] == owner_sub

    async def test_refreshed_token_includes_owner(
        self, app_client, db_pool, ed25519_keypair
    ):
        """After refresh, the new JWT still contains the owner claim."""
        private_pem, public_pem = ed25519_keypair
        agent_id = "refresh-owner-agent"
        owner_sub = "user-owner-456"
        secret = str(uuid.uuid4())
        secret_hash = hashlib.sha256(secret.encode()).hexdigest()

        now = int(time.time())
        jti = str(uuid.uuid4())

        # Insert a token record
        await db_pool.execute(
            """INSERT INTO agent_tokens (agent_id, jti, token_hash, issued_at, expires_at)
               VALUES ($1, $2, $3, to_timestamp($4), to_timestamp($5))""",
            agent_id,
            jti,
            secret_hash,
            now,
            now + 3600,
        )

        # Create a token WITH owner claim
        token = jwt.encode(
            {
                "sub": agent_id,
                "iss": "hill90-api",
                "aud": "hill90-akm",
                "exp": now + 3600,
                "iat": now,
                "jti": jti,
                "scopes": ["akm:read", "akm:write"],
                "owner": owner_sub,
            },
            private_pem,
            algorithm="EdDSA",
        )

        # Refresh
        resp = await app_client.post(
            "/internal/agents/refresh-token",
            headers={"Authorization": f"Bearer {token}"},
            json={"refresh_secret": secret},
        )
        assert resp.status_code == 200
        data = resp.json()
        new_token = data["token"]

        # Decode the refreshed token and verify owner is preserved
        decoded = jwt.decode(
            new_token,
            public_pem,
            algorithms=["EdDSA"],
            issuer="hill90-api",
            audience="hill90-akm",
        )
        assert decoded["owner"] == owner_sub
        assert decoded["sub"] == agent_id
        assert decoded["scopes"] == ["akm:read", "akm:write"]

    async def test_refreshed_token_without_owner_has_no_owner(
        self, app_client, db_pool, ed25519_keypair
    ):
        """Tokens without an owner claim don't gain one after refresh."""
        private_pem, public_pem = ed25519_keypair
        agent_id = "refresh-no-owner-agent"
        secret = str(uuid.uuid4())
        secret_hash = hashlib.sha256(secret.encode()).hexdigest()

        now = int(time.time())
        jti = str(uuid.uuid4())

        await db_pool.execute(
            """INSERT INTO agent_tokens (agent_id, jti, token_hash, issued_at, expires_at)
               VALUES ($1, $2, $3, to_timestamp($4), to_timestamp($5))""",
            agent_id,
            jti,
            secret_hash,
            now,
            now + 3600,
        )

        # Token WITHOUT owner claim
        token = jwt.encode(
            {
                "sub": agent_id,
                "iss": "hill90-api",
                "aud": "hill90-akm",
                "exp": now + 3600,
                "iat": now,
                "jti": jti,
                "scopes": ["akm:read", "akm:write"],
            },
            private_pem,
            algorithm="EdDSA",
        )

        resp = await app_client.post(
            "/internal/agents/refresh-token",
            headers={"Authorization": f"Bearer {token}"},
            json={"refresh_secret": secret},
        )
        assert resp.status_code == 200
        data = resp.json()
        new_token = data["token"]

        decoded = jwt.decode(
            new_token,
            public_pem,
            algorithms=["EdDSA"],
            issuer="hill90-api",
            audience="hill90-akm",
        )
        assert "owner" not in decoded

    async def test_agent_shared_retrieval_works_after_refresh(
        self, app_client, db_pool, ed25519_keypair
    ):
        """Agent can use shared retrieval endpoints with a refreshed token.

        End-to-end: create collection, add source, refresh token, search
        using the refreshed token — proves owner claim survives refresh
        and the shared search endpoint accepts it.
        """
        private_pem, _ = ed25519_keypair
        agent_id = "retrieval-after-refresh-agent"
        owner_sub = "retrieval-owner-789"
        secret = str(uuid.uuid4())
        secret_hash = hashlib.sha256(secret.encode()).hexdigest()

        now = int(time.time())
        jti = str(uuid.uuid4())

        # Insert token record
        await db_pool.execute(
            """INSERT INTO agent_tokens (agent_id, jti, token_hash, issued_at, expires_at)
               VALUES ($1, $2, $3, to_timestamp($4), to_timestamp($5))""",
            agent_id,
            jti,
            secret_hash,
            now,
            now + 3600,
        )

        # Create initial token with owner
        initial_token = jwt.encode(
            {
                "sub": agent_id,
                "iss": "hill90-api",
                "aud": "hill90-akm",
                "exp": now + 3600,
                "iat": now,
                "jti": jti,
                "scopes": ["akm:read", "akm:write"],
                "owner": owner_sub,
            },
            private_pem,
            algorithm="EdDSA",
        )

        # Create a shared collection visible to the agent
        await db_pool.execute(
            """INSERT INTO shared_collections (id, name, visibility, created_by)
               VALUES (gen_random_uuid(), 'Test Collection', 'shared', $1)""",
            owner_sub,
        )

        # Verify initial token works for shared search
        resp1 = await app_client.get(
            "/api/v1/shared/search",
            params={"q": "test"},
            headers={"Authorization": f"Bearer {initial_token}"},
        )
        assert resp1.status_code == 200

        # Refresh the token
        refresh_resp = await app_client.post(
            "/internal/agents/refresh-token",
            headers={"Authorization": f"Bearer {initial_token}"},
            json={"refresh_secret": secret},
        )
        assert refresh_resp.status_code == 200
        refreshed_token = refresh_resp.json()["token"]

        # Use the refreshed token for shared search — should still work
        resp2 = await app_client.get(
            "/api/v1/shared/search",
            params={"q": "test"},
            headers={"Authorization": f"Bearer {refreshed_token}"},
        )
        assert resp2.status_code == 200
        data = resp2.json()
        assert "query" in data
        assert data["query"] == "test"

        # Also verify collections endpoint works with refreshed token
        resp3 = await app_client.get(
            "/api/v1/shared/collections",
            headers={"Authorization": f"Bearer {refreshed_token}"},
        )
        assert resp3.status_code == 200
