/**
 * The coupling app#355 found missing: does the SET of env var names the api
 * puts into an agent's container actually contain the names the agentbox
 * IMAGE reads for its service endpoints and their credentials?
 *
 * WHY THIS, NOT "does the env contain AI_SERVICE_URL". That assertion would
 * just restate the one name app#355 happened to catch by hand. The actual
 * defect class is broader: nothing coupled what akm-token.ts and
 * model-router-token.ts assemble to what the agentbox image was ever
 * observed to read, so the two could rename, add or drop a variable
 * independently and nothing would notice until an agent silently couldn't
 * reach a service it thought it was configured for (app#353/#355: it
 * happened to still work, by coincidence of two independently-chosen
 * defaults agreeing — that is luck, not coupling).
 *
 * THE FIXTURE IS THE PROOF THIS ISN'T INVENTED FROM THIS REPO'S PYTHON.
 * `fixtures/agentbox-confirmed-env-vars.json` is what was read off the
 * BUILT IMAGE on the host, not off services/agentbox's source — see its own
 * header for provenance and how to re-derive it. Testing against a list
 * pulled from this repo's Python would just test that the repo agrees with
 * itself, which is exactly the property that was already silently false
 * for ~74 commits.
 *
 * SCOPE: this repo's confirmed fixture has 14 names. Six of them
 * (AGENT_ID, AGENT_CONFIG, WORK_TOKEN, AGENT_USE_TERMINAL,
 * CHAT_CALLBACK_TOKEN, TAVILY_API_KEY) are assembled directly in
 * routes/agents.ts and services/docker.ts from single, literal, unambiguous
 * names — there is no second name for the same concept for those to drift
 * against, which is the specific failure shape this test exists to catch.
 * This test covers the eight that ARE generated by the two token modules —
 * exactly where AI_SERVICE_URL/MODEL_ROUTER_URL actually drifted apart.
 */
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';

const { publicKey: akmPub, privateKey: akmPriv } = crypto.generateKeyPairSync('ed25519');
process.env.AKM_SIGNING_PRIVATE_KEY = akmPriv.export({ type: 'pkcs8', format: 'pem' }) as string;
void akmPub;

const { privateKey: mrPriv } = crypto.generateKeyPairSync('ed25519');
process.env.MODEL_ROUTER_SIGNING_PRIVATE_KEY = mrPriv.export({ type: 'pkcs8', format: 'pem' }) as string;

import { generateAgentAkmToken, getAkmEnvVars } from '../services/akm-token';
import { generateAgentModelRouterToken, getModelRouterEnvVars } from '../services/model-router-token';

const FIXTURE_PATH = path.join(__dirname, 'fixtures/agentbox-confirmed-env-vars.json');
const fixture: { envVars: string[] } = JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf-8'));

// The subset actually owned by akm-token.ts / model-router-token.ts — see
// the SCOPE note above for why the other six names aren't asserted here.
const NOT_OWNED_BY_TOKEN_MODULES = new Set([
  'AGENT_ID',
  'AGENT_CONFIG',
  'WORK_TOKEN',
  'AGENT_USE_TERMINAL',
  'CHAT_CALLBACK_TOKEN',
  'TAVILY_API_KEY',
]);

function namesOf(envVars: string[]): string[] {
  return envVars.map((kv) => kv.split('=')[0]);
}

describe('agent container env vs. the confirmed agentbox image contents', () => {
  it('the token modules together set every image-read name that is theirs to set', async () => {
    const akmToken = await generateAgentAkmToken({
      agentSlug: 'coupling-test-agent',
      agentUuid: 'coupling-test-uuid',
      scopes: ['akm:read', 'akm:write'],
      owner: 'coupling-test-owner',
    });
    const mrToken = await generateAgentModelRouterToken('coupling-test-agent', 'coupling-test-owner');

    const sentNames = new Set([
      ...namesOf(getAkmEnvVars(akmToken)),
      ...namesOf(getModelRouterEnvVars(mrToken)),
    ]);

    const expectedNames = fixture.envVars.filter((name) => !NOT_OWNED_BY_TOKEN_MODULES.has(name));
    // Sanity: the filter above must actually leave something to check, or
    // this test would pass vacuously the moment the fixture changed shape.
    expect(expectedNames.length).toBeGreaterThan(0);

    const missing = expectedNames.filter((name) => !sentNames.has(name));
    expect(missing).toEqual([]);
  });

  it('CONTROL: a name genuinely absent from what the token modules send is caught, not waved through', async () => {
    const akmToken = await generateAgentAkmToken({
      agentSlug: 'coupling-control-agent',
      agentUuid: 'coupling-control-uuid',
      scopes: ['akm:read', 'akm:write'],
      owner: 'coupling-control-owner',
    });
    const mrToken = await generateAgentModelRouterToken('coupling-control-agent', 'coupling-control-owner');

    const sentNames = new Set([
      ...namesOf(getAkmEnvVars(akmToken)),
      ...namesOf(getModelRouterEnvVars(mrToken)),
    ]);

    // A name the image was never observed to read and the api was never
    // meant to send — proves the comparison can fail, not just pass.
    expect(sentNames.has('THIS_NAME_DOES_NOT_EXIST_ANYWHERE')).toBe(false);
  });
});
