#!/usr/bin/env bash
# Hill90 local development stack.
#
#   ./scripts/local.sh up        generate config if needed, build, start, wait
#   ./scripts/local.sh down      stop, keep data
#   ./scripts/local.sh reset     stop and destroy volumes (databases included)
#   ./scripts/local.sh status    container + health summary
#   ./scripts/local.sh logs [svc]
#   ./scripts/local.sh init      generate .env.local and keys, then stop
#   ./scripts/local.sh agentbox  build the agentbox images (needed to run agents)
#
# Add --infra to any command to attach to a locally-running Hill90 infra stack
# (Traefik + observability) instead of running standalone:
#
#   ./scripts/local.sh up --infra
#
# Standalone is the default and needs nothing outside this repository.
#
# Everything is local. This script never touches a VPS, and there is no deploy
# path in this repository.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="$ROOT/compose/local.yml"
INFRA_FILE="$ROOT/compose/local.infra.yml"
ENV_FILE="$ROOT/.env.local"
KEY_DIR="$ROOT/compose/local/keys"

# --infra may appear anywhere in the arguments; strip it out and keep the rest.
INFRA=0
ARGS=()
for a in "$@"; do
  if [ "$a" = "--infra" ]; then INFRA=1; else ARGS+=("$a"); fi
done
set -- ${ARGS+"${ARGS[@]}"}

# Networks the Hill90 infra stack owns. The app owns hill90_agent_sandbox and
# hill90_docker_proxy, matching production, where docker-compose.api.yml is
# their sole creator.
# NETWORK_PREFIX mirrors the infra repo's .env.local (it defaults to hill90
# there too, and is set to hill90local for its local path).
NETPFX=$(grep -E '^NETWORK_PREFIX=' "$ROOT/.env.local" 2>/dev/null | cut -d= -f2)
NETPFX=${NETPFX:-hill90}
INFRA_NETWORKS=("${NETPFX}_edge" "${NETPFX}_internal" "${NETPFX}_agent_internal")

compose() {
  if [ "$INFRA" = "1" ]; then
    docker compose -f "$COMPOSE_FILE" -f "$INFRA_FILE" --env-file "$ENV_FILE" "$@"
  else
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" "$@"
  fi
}

# The overlay declares the shared networks external, so they must already
# exist. Compose's own error names one network at a time and says nothing about
# where it should come from.
check_infra_networks() {
  local missing=()
  for n in "${INFRA_NETWORKS[@]}"; do
    docker network inspect "$n" >/dev/null 2>&1 || missing+=("$n")
  done
  [ ${#missing[@]} -eq 0 ] && return 0
  cat >&2 <<EOF

--infra needs the Hill90 infrastructure stack running locally, but these
networks do not exist:

$(printf '  %s\n' "${missing[@]}")
Start the Hill90 local infra stack first, then run this again. To run without
it, drop --infra: the standalone stack creates its own networks and reaches
every service on published ports.

EOF
  return 1
}

rand() { openssl rand -hex 32; }

# Read a value out of .env.local (last definition wins, as with docker compose).
ev() { grep -E "^$1=" "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2-; }

# ---------------------------------------------------------------------------
# Ed25519 keypairs.
#
# The API mints agent tokens signed with these; the AI and knowledge services
# verify them against the matching public key. The private halves live in
# .env.local as \n-escaped PEM (services/api/src/services/akm-token.ts:21
# un-escapes them); the public halves are mounted read-only at /etc/akm.
# Freshly generated keys are fine — nothing depends on the originals.
# ---------------------------------------------------------------------------
gen_keys() {
  mkdir -p "$KEY_DIR"
  for name in akm model-router; do
    if [ ! -f "$KEY_DIR/$name-private.pem" ]; then
      openssl genpkey -algorithm ed25519 -out "$KEY_DIR/$name-private.pem" 2>/dev/null
      echo "  generated $name keypair"
    fi
  done
  # services/knowledge expects its public key at exactly /etc/akm/public.pem
  # (AKM_PUBLIC_KEY_PATH); the AI service expects model-router-public.pem.
  openssl pkey -in "$KEY_DIR/akm-private.pem"          -pubout -out "$KEY_DIR/public.pem"
  openssl pkey -in "$KEY_DIR/model-router-private.pem" -pubout -out "$KEY_DIR/model-router-public.pem"
  chmod 644 "$KEY_DIR"/*.pem
}

escape_pem() { awk '{printf "%s\\n", $0}' "$1"; }

gen_env() {
  if [ -f "$ENV_FILE" ]; then
    echo "  .env.local exists — leaving it alone"
    return
  fi
  echo "  writing .env.local"
  cat > "$ENV_FILE" <<EOF
# Hill90 local stack — generated by scripts/local.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Local-only credentials. Regenerate any time by deleting this file and
# re-running ./scripts/local.sh init. Not for any deployed environment.

# --- database ---
DB_USER=hill90
DB_PASSWORD=hill90

# --- object storage ---
MINIO_ROOT_USER=hill90admin
MINIO_ROOT_PASSWORD=hill90admin

# --- keycloak ---
KC_ADMIN_USERNAME=admin
KC_ADMIN_PASSWORD=admin
AUTH_KEYCLOAK_ID=hill90-ui
AUTH_KEYCLOAK_SECRET=local-dev-secret

# --- shared service tokens (must match across api/ai/knowledge) ---
AKM_INTERNAL_SERVICE_TOKEN=$(rand)
MODEL_ROUTER_INTERNAL_SERVICE_TOKEN=$(rand)
CHAT_CALLBACK_TOKEN=$(rand)
PROVIDER_KEY_ENCRYPTION_KEY=$(rand)
LITELLM_MASTER_KEY=sk-local-$(openssl rand -hex 16)
AUTH_SECRET=$(rand)

# --- agent token signing (Ed25519, public halves in compose/local/keys/) ---
AKM_SIGNING_PRIVATE_KEY=$(escape_pem "$KEY_DIR/akm-private.pem")
MODEL_ROUTER_SIGNING_PRIVATE_KEY=$(escape_pem "$KEY_DIR/model-router-private.pem")

# --- provider keys: REQUIRED FOR INFERENCE, optional to boot ---
# The stack starts and is fully browsable without these. Chat and embeddings
# will fail until at least one is real.
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
TAVILY_API_KEY=

# --- agent containers ---
# Absolute host path the API bind-mounts into each agentbox container. Must be
# a host path, since the Docker daemon resolves it, not the API container.
AGENTBOX_CONFIG_HOST_PATH=$ROOT/.local/agentbox-configs

# --- published ports (13000/18000 band, to avoid common conflicts) ---
PORT_UI=13000
PORT_API=13001
PORT_LITELLM=14000
PORT_POSTGRES=15432
PORT_AI=18000
PORT_MCP=18001
PORT_KNOWLEDGE=18002
PORT_KEYCLOAK=18080
PORT_MINIO=19000
PORT_MINIO_CONSOLE=19001

# --- infra overlay (./scripts/local.sh up --infra) ---------------------------
# Ignored unless --infra is used. These must match the Hill90 infra repo's own
# .env.local, since both stacks have to agree on network names and hostnames.
# The defaults below are the infra repo's local values.
NETWORK_PREFIX=hill90local
BASE_DOMAIN=localtest.me
HTTP_PORT=8080
UI_HOST=app
API_HOST=api
AUTH_HOST=auth
AI_HOST=ai
STORAGE_HOST=storage
EOF
}

cmd_init() {
  echo "Preparing local configuration..."
  gen_keys
  gen_env
  mkdir -p "$ROOT/.local/agentbox-configs"
  echo "Ready. Review $ENV_FILE, then: ./scripts/local.sh up"
}

wait_healthy() {
  local deadline=$((SECONDS + 300))
  echo "Waiting for services to become healthy (up to 5 min)..."
  while [ $SECONDS -lt $deadline ]; do
    local pending
    pending=$(compose ps --format json 2>/dev/null \
      | python3 -c '
import json,sys
bad=[]
for line in sys.stdin:
    line=line.strip()
    if not line: continue
    try: c=json.loads(line)
    except Exception: continue
    h=(c.get("Health") or "").lower(); s=(c.get("State") or "").lower()
    if h and h!="healthy": bad.append(c.get("Service","?")+":"+h)
    elif not h and s!="running": bad.append(c.get("Service","?")+":"+s)
print(" ".join(bad))' 2>/dev/null || echo "unknown")
    if [ -z "$pending" ]; then
      echo "All services healthy."
      return 0
    fi
    printf "\r  waiting: %-70s" "$pending"
    sleep 5
  done
  echo
  echo "Timed out. Current state:"
  compose ps
  return 1
}

# ---------------------------------------------------------------------------
# Port preflight.
#
# Every published port is configurable in .env.local, but a clash otherwise
# surfaces as a bare Docker error part-way through startup, after some
# containers are already running:
#
#   Bind for 0.0.0.0:14000 failed: port is already allocated
#
# The chosen band avoids the usual suspects, but nothing can avoid every host.
# Check up front and say which variable to change.
# ---------------------------------------------------------------------------
port_in_use() { (exec 3<>/dev/tcp/127.0.0.1/"$1") 2>/dev/null; }

check_ports() {
  # Ports this stack is already publishing are not conflicts — that is just a
  # re-run of `up` against a running stack.
  local ours
  ours=$(docker ps --filter 'name=hill90-' --format '{{.Ports}}' 2>/dev/null \
         | grep -oE '0\.0\.0\.0:[0-9]+' | cut -d: -f2 | sort -u)

  local conflicts=""
  while IFS='=' read -r var port; do
    [ -n "$port" ] || continue
    grep -qx "$port" <<<"$ours" && continue
    if port_in_use "$port"; then
      local holder
      holder=$(docker ps --format '{{.Names}}\t{{.Ports}}' 2>/dev/null \
               | grep ":$port->" | cut -f1 | head -1)
      conflicts+="  $port  ($var)${holder:+  — held by container '$holder'}"$'\n'
    fi
  done < <(grep -E '^PORT_[A-Z_]+=[0-9]+' "$ENV_FILE")

  [ -z "$conflicts" ] && return 0

  cat >&2 <<EOF

Port conflict — these are already in use on this host:

$conflicts
Edit $ENV_FILE, change the listed PORT_* variable(s) to a free port,
then run this again. Nothing was started.

EOF
  return 1
}

cmd_up() {
  [ -f "$ENV_FILE" ] || cmd_init
  [ "$INFRA" = "1" ] && { check_infra_networks || exit 1; }
  check_ports || exit 1
  mkdir -p "$ROOT/.local/agentbox-configs"
  gen_keys
  compose build
  compose up -d
  wait_healthy || true
  echo
  cmd_status
  local dom port
  dom=$(ev BASE_DOMAIN); dom=${dom:-localtest.me}
  port=$(ev HTTP_PORT);  port=${port:-8080}
  cat <<EOF

  UI              http://localhost:$(grep -E '^PORT_UI=' "$ENV_FILE" | cut -d= -f2)
  API             http://localhost:$(grep -E '^PORT_API=' "$ENV_FILE" | cut -d= -f2)/health
  Keycloak admin  http://localhost:$(grep -E '^PORT_KEYCLOAK=' "$ENV_FILE" | cut -d= -f2)  (admin/admin)
  MinIO console   http://localhost:$(grep -E '^PORT_MINIO_CONSOLE=' "$ENV_FILE" | cut -d= -f2)
EOF
  [ "$INFRA" = "1" ] && cat <<EOF

  Through Traefik (Hill90 infra):
    UI            http://$(ev UI_HOST).$dom:$port
    API           http://$(ev API_HOST).$dom:$port/health
    Keycloak      http://$(ev AUTH_HOST).$dom:$port
    MCP gateway   http://$(ev AI_HOST).$dom:$port/mcp
    MinIO console http://$(ev STORAGE_HOST).$dom:$port
EOF
  cat <<EOF

  Log in to the UI as  dev / dev

EOF
}

cmd_status() {
  compose ps --format 'table {{.Service}}\t{{.State}}\t{{.Status}}\t{{.Ports}}'
}

cmd_agentbox() {
  # agentbox is not a compose service — the API creates one container per agent
  # from these images (services/api/src/services/docker.ts:78-146). The base
  # image copies the akm CLI out of hill90/knowledge, so that must exist first.
  echo "Building agentbox images (slow: installs Node, Playwright, oh-my-zsh)..."
  docker build -t hill90/knowledge:latest "$ROOT/services/knowledge"
  docker build -t hill90/agentbox:latest  "$ROOT/services/agentbox"
  docker build -t hill90/agentbox-monitor:latest -f "$ROOT/services/agentbox/Dockerfile.monitor" "$ROOT/services/agentbox"
  echo "Done. hill90/agentbox:latest is what the API launches by default."
}

case "${1:-up}" in
  init)     cmd_init ;;
  up)       cmd_up ;;
  down)     compose down ;;
  reset)    compose down -v; rm -rf "$ROOT/.local/agentbox-configs"; echo "Volumes destroyed." ;;
  status)   cmd_status ;;
  logs)     shift; compose logs -f "$@" ;;
  agentbox) cmd_agentbox ;;
  realm)    echo "Edit compose/local/keycloak/realm-local.json, then: ./scripts/local.sh reset && ./scripts/local.sh up" ;;
  *)        sed -n '2,12p' "${BASH_SOURCE[0]}"; exit 1 ;;
esac
