#!/usr/bin/env bash
# Every host path bind-mounted by deploy/compose must exist, or be git-ignored.
#
# WHY THIS EXISTS
#
# `deploy/compose/overrides/local.auth.yml` mounts
# `../../../compose/local/keycloak/realm-local.json` — it reaches OUT of
# deploy/compose and into the top-level compose/ directory. So compose/ looks like
# a leftover from before the layout collapsed, and is not one: that file is
# load-bearing for the DEFAULT local path, not just for `--standalone`.
#
# The failure mode is quiet, which is why it needs a test rather than a comment.
# Delete or move a bind-mounted FILE and Docker does not error — it creates a
# DIRECTORY at that path. Keycloak then starts with an import directory containing
# a directory instead of a realm, imports no realm, and local login fails with
# something that looks like a Keycloak problem several steps from the cause.
#
# THE RULE
#
# A bind-mounted host path must either exist in the working tree, or be ignored by
# git. Ignored means "created at runtime" — `compose/local/keys` is generated by
# scripts/local.sh before it brings anything up, so it is legitimately absent in a
# fresh clone. Anything else absent is a broken reference.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COMPOSE_DIRS=("$ROOT/deploy/compose/prod" "$ROOT/deploy/compose/overrides")

missing=()
checked=0
ignored=0

for dir in "${COMPOSE_DIRS[@]}"; do
  [ -d "$dir" ] || { echo "FAIL: no such compose directory: $dir" >&2; exit 2; }

  for f in "$dir"/*.yml; do
    [ -e "$f" ] || continue

    # Bind mounts written relative to the compose file, e.g.
    #   - ../../../compose/local/keycloak/realm-local.json:/opt/...:ro
    # Anything not starting with . is a named volume, not a host path.
    while IFS= read -r spec; do
      [ -n "$spec" ] || continue

      host="${spec%%:*}"
      abs="$dir/$host"

      # Normalise without requiring the path to exist (realpath -m is not on
      # macOS by default, and `cd` cannot enter a missing directory).
      norm="$(python3 -c 'import os,sys; print(os.path.normpath(sys.argv[1]))' "$abs")"
      rel="${norm#"$ROOT"/}"

      checked=$((checked + 1))

      if [ -e "$norm" ]; then
        continue
      fi

      # Absent is acceptable only if git deliberately ignores it.
      #
      # Both forms are tried on purpose. `.gitignore` has `compose/local/keys/`
      # with a trailing slash, which only matches directories — and git cannot
      # tell that a path which does not exist is a directory, so `check-ignore`
      # on the bare path returns no match. Checking `$rel/` as well is what makes
      # a directory-only ignore rule recognisable here.
      if git -C "$ROOT" check-ignore -q "$rel" 2>/dev/null \
         || git -C "$ROOT" check-ignore -q "$rel/" 2>/dev/null; then
        ignored=$((ignored + 1))
        echo "runtime  $rel  (git-ignored, created by scripts/local.sh)"
        continue
      fi

      missing+=("$(basename "$f"): $host -> $rel")
    done < <(grep -oE '^[[:space:]]+-[[:space:]]+\.[^:]+:[^[:space:]]+' "$f" \
             | sed -E 's/^[[:space:]]+-[[:space:]]+//' || true)
  done
done

echo "checked ${checked} bind mounts (${ignored} runtime-created)"

if [ ${#missing[@]} -gt 0 ]; then
  echo "COMPOSE_MOUNT_MISSING"
  for m in "${missing[@]}"; do
    echo "  - $m"
  done
  echo
  echo "A bind-mounted host path does not exist and is not git-ignored."
  echo "Docker will silently create a DIRECTORY there rather than failing, so the"
  echo "symptom will appear later and somewhere else. If a file moved, update the"
  echo "compose reference; if it was deleted, say what made it dead first."
  exit 1
fi

echo "COMPOSE_MOUNTS_RESOLVE"
