#!/usr/bin/env bats
#
# The top-level compose/ directory looks like a leftover and is not one.
#
# `deploy/compose/overrides/local.auth.yml` mounts
# `../../../compose/local/keycloak/realm-local.json`, so the DEFAULT local path
# depends on a file outside deploy/compose. These tests exist so that deleting or
# relocating it fails here rather than in a confusing Keycloak startup.

setup() {
  REPO_ROOT="$(cd "${BATS_TEST_DIRNAME}/../.." && pwd)"
  CHECK="${REPO_ROOT}/tests/scripts/compose-mounts-check.sh"
}

@test "every bind-mounted host path in deploy/compose resolves" {
  run "$CHECK"
  [ "$status" -eq 0 ]
  [[ "$output" == *"COMPOSE_MOUNTS_RESOLVE"* ]]
}

@test "the check fails when a mounted file is moved away" {
  target="${REPO_ROOT}/compose/local/keycloak/realm-local.json"
  [ -f "$target" ]

  stash="${BATS_TEST_TMPDIR}/realm-local.json"
  mv "$target" "$stash"

  run "$CHECK"
  mv "$stash" "$target"

  [ "$status" -eq 1 ]
  [[ "$output" == *"COMPOSE_MOUNT_MISSING"* ]]
  [[ "$output" == *"realm-local.json"* ]]
}

@test "a git-ignored mount path is treated as runtime-created, not missing" {
  # compose/local/keys is generated by scripts/local.sh and is git-ignored, so it is
  # legitimately absent in a fresh clone. .gitignore lists it with a trailing slash,
  # which matches directories only — and git cannot tell that a non-existent path is
  # a directory, so the check must try both forms.
  #
  # This test used to depend on the directory being ABSENT, which made it pass only
  # on a machine where local had never been brought up. Running the local stack for
  # the first time in weeks created the keys and the test started failing — the
  # assertion was about the environment, not the code. It now creates the condition
  # deliberately and restores whatever was there.
  keys="${REPO_ROOT}/compose/local/keys"
  stash="${BATS_TEST_TMPDIR}/keys-stash"
  moved=0
  if [ -e "$keys" ]; then mv "$keys" "$stash"; moved=1; fi

  run "$CHECK"
  status_seen="$status"; output_seen="$output"

  if [ "$moved" -eq 1 ]; then rm -rf "$keys"; mv "$stash" "$keys"; fi

  [ "$status_seen" -eq 0 ]
  [[ "$output_seen" == *"compose/local/keys"* ]]
  [[ "$output_seen" == *"git-ignored"* ]]
}

@test "the check still passes when the git-ignored path DOES exist" {
  # The other half: once local.sh has run, the path exists and is simply OK. Both
  # states must pass, and the earlier version only covered one of them.
  keys="${REPO_ROOT}/compose/local/keys"
  created=0
  if [ ! -e "$keys" ]; then mkdir -p "$keys"; created=1; fi

  run "$CHECK"
  status_seen="$status"; output_seen="$output"

  if [ "$created" -eq 1 ]; then rmdir "$keys" 2>/dev/null || true; fi

  [ "$status_seen" -eq 0 ]
  [[ "$output_seen" == *"COMPOSE_MOUNTS_RESOLVE"* ]]
}

@test "the tenant override really is the thing that reaches into compose/" {
  # If this mount ever moves under deploy/compose/overrides/, this test should be
  # updated together with it — and the move is then safe, which is the point.
  run grep -q 'compose/local/keycloak/realm-local.json' \
      "${REPO_ROOT}/deploy/compose/overrides/local.auth.yml"
  [ "$status" -eq 0 ]
}

@test "realm-local.json still carries the local-only dev account" {
  # This file is why compose/ cannot simply be deleted: it bakes in the
  # dev/dev@localhost account that local development depends on and production
  # deliberately lacks.
  run grep -q '"username"' "${REPO_ROOT}/compose/local/keycloak/realm-local.json"
  [ "$status" -eq 0 ]

  run grep -q 'dev@localhost' "${REPO_ROOT}/compose/local/keycloak/realm-local.json"
  [ "$status" -eq 0 ]
}
